### PR TITLE
Fix domain

### PR DESCRIPTION
**Pull request by MartijnBogaert**
I don't think the inverses are necessary and just some renames

### CODE REVIEW

**Review by claire-lovisa — APPROVED** [review]
Oh yes of course ! Should we add some inverse relationships ? Or we just wait and see if we need them later on ?

**Review by MartijnBogaert — COMMENTED** [review]
> Oh yes of course ! Should we add some inverse relationships ? Or we just wait and see if we need them later on ? 

was thinking the same thing, i'll add some, just to be safe

**Comment by MartijnBogaert** [comment]
@claire-lovisa inverses added
maybe we should also let an annotation have multiple validations? as if multiple people can validate

**Comment by claire-lovisa** [comment]
I feel like only one validation would make more sense, we'd end up in a weird state if someone validates and someone denies :thinking:

**Review by claire-lovisa — APPROVED** [review]

**Review by MartijnBogaert — COMMENTED** [review]
> I feel like only one validation would make more sense, we'd end up in a weird state if someone validates and someone denies :thinking: 
 

sure, we'll leave it as is then!

**Pull request merged**
